// swift-tools-version: 6.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

// =================================================================
// || Do not edit! This file is generated by node/zipFramework.js ||
// =================================================================

import PackageDescription

let package = Package(
  name: "FuegoOnAppleSilicon",
  platforms: [.iOS(.v14), .macOS(.v13), .visionOS(.v1)],
  products: [
    .library(
      name: "FuegoOnAppleSilicon",
      targets: ["FuegoOnAppleSilicon", "FuegoCBridge"]
    ),
  ],
  targets: [
    .binaryTarget(
      name: "FuegoXCFramework",
      url: "https://github.com/mesqueeb/FuegoOnAppleSilicon/releases/download/v1.1.2/Fuego-1.1.2.xcframework.zip",
      checksum: "a5f5844a4ce754e8360de76b01a9a20140fefe2eed85b1f44d69987d7c94c4f3"
    ),
    .target(
      name: "FuegoCBridge",
      dependencies: ["FuegoXCFramework"],
      path: "FuegoOnAppleSilicon/Sources/CBridge"
    ),
    .target(
      name: "FuegoOnAppleSilicon",
      dependencies: ["FuegoCBridge"],
      path: "FuegoOnAppleSilicon/Sources/SwiftBridge"
    ),
    .testTarget(
      name: "FuegoOnAppleSiliconTests",
      dependencies: ["FuegoOnAppleSilicon"],
      path: "FuegoOnAppleSilicon/Tests"
    ),
  ]
)
