// swift-tools-version: 6.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

// =================================================================
// || Do not edit! This file is generated by node/zipFramework.js ||
// =================================================================

import PackageDescription


/// This `Package.swift` exists to be able to import the package in an Xcode project in the same repository.
///
/// Compared to the repository root `Package.swift`, everything is the same but the target paths.
let package = Package(
  name: "FuegoOnAppleSilicon",
  platforms: [.iOS(.v14), .macOS(.v13), .visionOS(.v1)],
  products: [
    .library(
      name: "FuegoOnAppleSilicon",
      targets: ["FuegoOnAppleSilicon", "FuegoCBridge"]
    ),
  ],
  targets: [
    .binaryTarget(
      name: "FuegoXCFramework",
      url: "https://github.com/mesqueeb/FuegoOnAppleSilicon/releases/download/v1.0.1/Fuego-1.0.1.xcframework.zip",
      checksum: "61aa32f06ef74d993122845395720adf1149a978849bb9e8d7bb41e3ed454c19"
    ),
    .target(
      name: "FuegoCBridge",
      dependencies: ["FuegoXCFramework"],
      path: "Sources/CBridge"
    ),
    .target(
      name: "FuegoOnAppleSilicon",
      dependencies: ["FuegoCBridge"],
      path: "Sources/SwiftBridge"
    ),
    .testTarget(
      name: "FuegoOnAppleSiliconTests",
      dependencies: ["FuegoOnAppleSilicon"],
      path: "Tests"
    ),
  ]
)
