import select from "@inquirer/select"
import { execSync } from "node:child_process"
import { writeFileSync } from "node:fs"
import { createRequire } from "node:module"
import { join, basename } from "node:path"
import { replaceRegex } from "replace-regex"
import semver from "semver"

const require = createRequire(import.meta.url)
const { version } = require("../package.json")

const bump = await select({
  message: "Select the version bump:",
  choices: ["patch", "minor", "major"].map((value) => ({ name: value, value })),
})

const PATH_ROOT = join(process.cwd())
const PATH_BUILD = join(PATH_ROOT, "./build")

const nextVersion = semver.inc(version, bump)
const frameworkPath = join(PATH_BUILD, "./Fuego.xcframework")
const zipFilename = `Fuego-${nextVersion}.xcframework.zip`
const zipFullPath = join(PATH_BUILD, `./${zipFilename}`)

// Change directory to the build folder to create the zip
const frameworkName = basename(frameworkPath)

execSync(`cd ${PATH_BUILD} && zip -r ${zipFilename} ${frameworkName}`, {
  stdio: "inherit",
})

const zipChecksum = execSync(`swift package compute-checksum ${zipFullPath}`).toString().trim()

const manifestContent = `// swift-tools-version: 6.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

// =================================================================
// || Do not edit! This file is generated by node/zipFramework.js ||
// =================================================================

import PackageDescription

let package = Package(
  name: "FuegoOnAppleSilicon",
  platforms: [.iOS(.v14), .macOS(.v13), .visionOS(.v1)],
  products: [
    .library(
      name: "FuegoOnAppleSilicon",
      targets: ["FuegoOnAppleSilicon", "FuegoCBridge"]
    ),
  ],
  targets: [
    .binaryTarget(
      name: "FuegoXCFramework",
      url: "https://github.com/mesqueeb/FuegoOnAppleSilicon/releases/download/v${nextVersion}/${zipFilename}",
      checksum: "${zipChecksum}"
    ),
    .target(
      name: "FuegoCBridge",
      dependencies: ["FuegoXCFramework"],
      path: "Sources/CBridge"
    ),
    .target(
      name: "FuegoOnAppleSilicon",
      dependencies: ["FuegoCBridge"],
      path: "Sources/SwiftBridge"
    ),
    .testTarget(
      name: "FuegoOnAppleSiliconTests",
      dependencies: ["FuegoOnAppleSilicon"],
      path: "Tests"
    ),
  ]
)
`

// Write the updated Package.swift
writeFileSync(join(PATH_ROOT, "Package.swift"), manifestContent)

await replaceRegex({
  files: join(PATH_ROOT, "README.md"),
  from: /from: "\d+\.\d+\.\d+"/g,
  to: `from: "${nextVersion}"`,
})

execSync(`git add .`, { stdio: "inherit" })
execSync(`git commit -m "chore: 🎉 Release version ${nextVersion}"`, {
  stdio: "inherit",
})

execSync(`bumpp --release ${bump} --no-push --yes`, { stdio: "inherit" })
execSync(`git push --follow-tags`, { stdio: "inherit" })
// the zip is attached to the release so the binaryTarget url in Package.swift resolves right away
// GitHub only lists pull requests in generated notes, so list the commits ourselves like np did
const notes = execSync(`git log --pretty="- %s  %h" v${version}..HEAD~1`).toString().trim()
execSync(`gh release create v${nextVersion} --generate-notes --notes ${JSON.stringify(notes)} ${zipFullPath}`, { stdio: "inherit" })
console.log(`Released v${nextVersion} with ${zipFilename} attached.`)
